---
# tasks file for activemq_install

# Create user account used by activemq

- name: Create activemq user
  user:
    name: "{{ activemq_user }}"
    shell: /bin/bash

## being process to install activemq

- name: Check install dir exists
  file:
    path: "{{ activemq_install_dir }}"
    state: directory

- name: Download Apache Activemq {{ activemq_version }}
  get_url:
   url: "{{ activemq_download_url }}"
   dest: "{{ activemq_install_dir }}"

- name: unzip activemq binary
  unarchive:
    src: '{{ activemq_install_dir }}/{{ activemq_file_name }}'
    dest: '{{ activemq_install_dir }}'
    copy: no
    extra_opts: "--strip-components=1"    

- name: change ownership on activemq dir to {{ activemq_user }}
  file:
    path: "{{ activemq_install_dir }}"
    state: directory
    mode: 0755
    owner: "{{ activemq_user }}"
    group: "{{ activemq_user }}"
    recurse: yes

## clean up

- name: Clear up downloaded activemq binary
  file:
    path: "{{ activemq_install_dir }}/{{ activemq_file_name }}"
    state: absent