---
- name: Checking to see in activemq is alread present
  stat:
    path: "{{ activemq_install_dir }}/bin/activemq"
  register: isInstalled

- name:
  debug:
    msg: "ActiveMQ appears already installed on path {{ activemq_install_dir }}"
  when: isInstalled.stat.exists

- name: Create activemq user
  user:
    name: "{{ activemq_user }}"
    shell: /bin/bash
  when: not isInstalled.stat.exists

## being process to install activemq

- name: Check install dir exists
  file:
    path: "{{ activemq_install_dir }}"
    state: directory
    owner: "{{ activemq_user }}"
    group: "{{ activemq_user }}"
  when: not isInstalled.stat.exists

- name: Download Apache Activemq {{ activemq_version }}
  get_url:
    url: "{{ activemq_download_url }}"
    dest: "{{ activemq_install_dir }}"
  when: not isInstalled.stat.exists

- name: unzip activemq binary
  unarchive:
    src: '{{ activemq_install_dir }}/{{ activemq_file_name }}'
    dest: '{{ activemq_install_dir }}'
    copy: false
    extra_opts: "--strip-components=1"
  when: not isInstalled.stat.exists

## clean up

- name: Clear up downloaded activemq binary
  file:
    path: "{{ activemq_install_dir }}/{{ activemq_file_name }}"
    state: absent
  when: not isInstalled.stat.exists


- name: change ownership on activemq dir to {{ activemq_user }}
  file:
    path: "{{ activemq_install_dir }}"
    state: directory
    mode: 0755
    owner: "{{ activemq_user }}"
    group: "{{ activemq_user }}"
    recurse: true
  when: not isInstalled.stat.exists
