---

- name: Create activemq user
  user:
    name: "{{ activemq_user }}"
    shell: /bin/bash

## being process to install activemq

- name: Check install dir exists
  file:
    path: "{{ activemq_install_dir }}"
    state: directory
    owner: "{{ activemq_user }}"
    group: "{{ activemq_user }}"
  register: create_install_dir_result
  become: true

- name: Download Apache Activemq {{ activemq_version }}
  get_url:
    url: "{{ activemq_download_url }}"
    dest: "{{ activemq_install_dir }}"
  become: true
  when: create_install_dir_result.changed

- name: unzip activemq binary
  unarchive:
    src: '{{ activemq_install_dir }}/{{ activemq_file_name }}'
    dest: '{{ activemq_install_dir }}'
    copy: false
    extra_opts: "--strip-components=1"
  become: true
  when: create_install_dir_result.changed

## clean up

- name: Clear up downloaded activemq binary
  file:
    path: "{{ activemq_install_dir }}/{{ activemq_file_name }}"
    state: absent
  become: true
  when: create_install_dir_result.changed


- name: change ownership on activemq dir to {{ activemq_user }}
  file:
    path: "{{ activemq_install_dir }}"
    state: directory
    mode: 0755
    owner: "{{ activemq_user }}"
    group: "{{ activemq_user }}"
    recurse: true
  become: true
